name: Build
on: [push, workflow_dispatch]

jobs:
  unit:
    name: Build
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu, windows]
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version-file: ./go.mod
      - run: go run ./...
